In [0]:
import os
import math
import pandas as pd
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).


In [0]:
cd "/content/Drive/My Drive/Spring 2019/ML/sample for project"

/content/Drive/My Drive/Spring 2019/ML/sample for project


In [0]:
df=pd.read_csv('b4vectorize.csv')

In [0]:
list(df)

In [0]:
df.shape

(11429, 104)

1. Drop the Unnamed coloumns
2. Creete (1,0) labels by .apply
3. vectorize the postText (close session before vectorizing!)
4. concat the vectorized table with image represenation table (columns)
5. (optional) normalize the image rep. table [0, 1] (on a SEPERATE DF)

In [0]:
#drop unnamed columns
df1 = df[df.columns.drop(list(df.filter(regex='Unnamed:')))]
list(df1)

['id',
 'postMedia',
 'postText',
 'postTimestamp',
 'targetCaptions',
 'targetDescription',
 'targetKeywords',
 'targetParagraphs',
 'targetTitle',
 'truthClass',
 'truthJudgments',
 'truthMean',
 'truthMedian',
 'truthMode',
 'person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'dining table',
 'toilet',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keybo

In [0]:
#create binary labels for outcome
def binary_formula(x):
  if x == 'clickbait': return 1
  else: return 0

df1['truthClassInt'] = df1.apply(lambda row: binary_formula(row['truthClass']), axis = 1)
df1


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


id                           postMedia  \
0      609297109095972864        media/609297109095972864.jpg   
1      608688782821453824        media/608688782821453825.jpg   
2      609551038983475200        media/609551038983475201.png   
3      609447408955719680        media/609447408955719681.jpg   
4      609046214554755072        media/609046214554755073.jpg   
5      609762671554990080        media/609762671554990080.jpg   
6      609998126737395712        media/609998126737395712.jpg   
7      608926452596273152        media/608926452596273152.jpg   
8      608576531456249856        media/608576531456249856.jpg   
9      609372816568360960        media/609372816568360960.jpg   
10     610103181578764288        media/610103181578764291.jpg   
11     609425861561962496        media/609425861561962496.png   
12     608658774769958912        media/608658774769958912.jpg   
13     609396415681445888        media/609396415681445888.png   
14     609337131698229248        media/609337131698229249.jpg   
15     608315579913629696        media/608315579913629696.png   
16     608347082844438528        media/608347082844438530.jpg   
17     609507025555357696        media/609507025555357696.png   
18     609141582290292736        media/609141582290292736.jpg   
19     607867811352969216        media/607867811352969216.jpg   
20     608953025017839616        media/608953025017839616.jpg   
21     610065075462930432        media/610065075462930432.jpg   
22     607974158765400064        media/607974158765400065.jpg   
23     609680396956094464        media/609680396956094464.jpg   
24     610149872059195392        media/610149872059195392.jpg   
25     609865605856899072        media/609865605856899072.jpg   
26     609204522263650304        media/609204522263650304.png   
27     608294260027346944        media/608294260027346944.jpg   
28     609780343680409600        media/609780343680409600.jpg   
29     609220830501933056        media/609220830501933056.jpg   
...                   ...                                 ...   
11399  805534069371105280  media/photo_805534066820968448.jpg   
11400  805520525044760576  media/photo_805520398511022080.jpg   
11401  805494636907270144  media/photo_805494634466185216.jpg   
11402  805491234672439296  media/photo_805491232898052096.jpg   
11403  805471736447705088  media/photo_805466700267171840.jpg   
11404  805396238006939648  media/photo_805396234542477314.jpg   
11405  805252057083117568  media/photo_805252054981758976.jpg   
11406  805138811126693888  media/photo_805138806793969664.jpg   
11407  805113696871743488  media/photo_805113694757584896.jpg   
11408  805102353812717568  media/photo_805102351333945344.jpg   
11409  805086954643722240  media/photo_805086951774654464.jpg   
11410  805072130266296320  media/photo_805072128471142400.jpg   
11411  805069338776576000  media/photo_805069335479795714.jpg   
11412  805036327179845632  media/photo_805036325300736000.jpg   
11413  804954596284178432  media/photo_804954592345780224.jpg   
11414  804920604247937024  media/photo_804920601601277952.jpg   
11415  804868006346162176  media/photo_804868003963764737.jpg   
11416  804843363904143360  media/photo_804843354622136320.jpg   
11417  804787480327294976  media/photo_804787478569717760.jpg   
11418  804595968180097024  media/photo_804595965919232000.jpg   
11419  804592931319463936  media/photo_804592928417021952.jpg   
11420  804543366516080640  media/photo_804543364242796544.jpg   
11421  804495554583662592  media/photo_804495551370694656.jpg   
11422  804486528013664256  media/photo_804486525392130048.jpg   
11423  804455772960624640  media/photo_804455668702990337.jpg   
11424  804379539036114944  media/photo_804379537232564224.jpg   
11425  804364802940436480  media/photo_804364766764417024.jpg   
11426  804250183642976256  media/photo_804240867972304896.jpg   
11427  804134698729385984  media/photo_804133521023324160.jpg   
11428  804126501117435904  media/photo_804125377400553474.

In [0]:
for col in df1.columns: 
    print(col) 

In [0]:
#vectorize post text
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
vectorizer = CountVectorizer()  
X = vectorizer.fit_transform(df1['postText'])
X

<11429x13668 sparse matrix of type '<class 'numpy.int64'>'
	with 125044 stored elements in Compressed Sparse Row format>

In [0]:
temp = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names())


In [0]:
#Examine all the column words in vocabulary
pd.set_option('display.max_columns', None)
temp.head()

Output hidden; open in https://colab.research.google.com to view.

In [0]:
#create new dataframe for assessing models with just text  and also for linear regression 
base = pd.merge(temp, df1['truthClassInt'], left_index=True, right_index=True)
#base1 = pd.merge(temp, df1['truthMean'], left_index=True, right_index=True)


In [0]:
base.shape

(11429, 13669)

In [0]:
#concatenate id in original table to this vectorized table, it will merge by index by default. index does not have a column name

final = pd.merge(temp, df1, left_index=True, right_index=True)
final


00  016  070  070shake  10  100  1000  10000  100000  1000000  ...  \
0       0    0    0         0   0    0     0      0       0        0  ...   
1       0    0    0         0   0    0     0      0       0        0  ...   
2       1    0    0         0   0    0     0      0       0        0  ...   
3       0    0    0         0   0    0     0      0       0        0  ...   
4       0    0    0         0   0    0     0      0       0        0  ...   
5       0    0    0         0   0    0     0      0       0        0  ...   
6       0    0    0         0   0    0     0      0       0        0  ...   
7       0    0    0         0   0    0     0      0       0        0  ...   
8       0    0    0         0   0    0     0      0       0        0  ...   
9       0    0    0         0   0    0     0      0       0        0  ...   
10      0    0    0         0   0    0     0      0       0        0  ...   
11      0    0    0         0   0    0     0      0       0        0  ...   
12      0    0    0         0   0    0     0      0       0        0  ...   
13      0    0    0         0   0    0     0      0       0        0  ...   
14      0    0    0         0   0    0     0      0       0        0  ...   
15      0    0    0         0   0    0     0      0       0        0  ...   
16      0    0    0         0   0    0     0      0       0        0  ...   
17      0    0    0         0   0    0     0      0       0        0  ...   
18      0    0    0         0   0    0     0      0       0        0  ...   
19      0    0    0         0   0    0     0      0       0        0  ...   
20      0    0    0         0   0    0     0      0       0        0  ...   
21      0    0    0         0   0    0     0      0       0        0  ...   
22      0    0    0         0   0    0     0      0       0        0  ...   
23      0    0    0         0   0    0     0      0       0        0  ...   
24      0    0    0         0   0    0     0      0       0        0  ...   
25      0    0    0         0   0    0     0      0       0        0  ...   
26      0    0    0         0   0    0     0      0       0        0  ...   
27      0    0    0         0   0    0     0      0       0        0  ...   
28      0    0    0         0   0    0     0      0       0        0  ...   
29      0    0    0         0   0    0     0      0       0        0  ...   
...    ..  ...  ...       ...  ..  ...   ...    ...     ...      ...  ...   
11399   0    0    0         0   0    0     0      0       0        0  ...   
11400   0    0    0         0   0    0     0      0       0        0  ...   
11401   0    0    0         0   0    0     0      0       0        0  ...   
11402   0    0    0         0   0    0     0      0       0        0  ...   
11403   0    0    0         0   0    0     0      0       0        0  ...   
11404   0    0    0         0   0    0     0      0       0        0  ...   
11405   0    0    0         0   0    0     0      0       0        0  ...   
11406   0    0    0         0   0    0     0      0       0        0  ...   
11407   0    0    0         0   0    0     0      0       0        0  ...   
11408   0    0    0         0   0    0     0      0       0        0  ...   
11409   0    0    0         0   0    0     0      0       0        0  ...   
11410   0    0    0         0   0    0     0      0       0        0  ...   
11411   0    0    0         0   0    0     0      0       0        0  ...   
11412   0    0    0         0   0    0     0      0       0        0  ...   
11413   0    0    0         0   0    0     0      0       0        0  ...   
11414   0    0    0         0   0    0     0      0       0        0  ...   
11415   0    0    0         0   0    0     0      0       0        0  ...   
11416   0    0    0         0   0    0     0      0       0        0  ...   
11417   0    0    0         0   0    0     0      0       0        0  ...   
11418   0    0    0         0   0    0     1      0       0        0  ...   
114

In [0]:
#save to csv file
final.to_csv(r'/content/Drive/My Drive/Spring 2019/ML/sample for project/final_clipping.csv', index=False)

In [0]:
image_col = []

counter = 0
for col in final.columns:
  if counter > 13681:
    print(col)
    image_col.append(col)
  counter +=1

person_y
bicycle
car_y
motorcycle
airplane
bus
train_y
truck_y
boat_y
traffic light
fire hydrant
stop sign
parking meter
bench_y
bird_y
cat_y
dog_y
horse
sheep_y
cow_y
elephant
bear_y
zebra_y
giraffe
backpack_y
umbrella_y
handbag_y
tie_y
suitcase
frisbee
skis
snowboard
sports ball
kite
baseball bat
baseball glove
skateboard_y
surfboard
tennis racket
bottle
wine glass
cup_y
fork_y
knife_y
spoon
bowl_y
banana_y
apple
sandwich_y
orange
broccoli
carrot
hot dog
pizza_y
donut_y
cake_y
chair_y
couch
potted plant
bed_y
dining table
toilet_y
tv_y
laptop_y
mouse
remote
keyboard_y
cell phone
microwave
oven_y
toaster_y
sink_y
refrigerator
book_y
clock_y
vase
scissors
teddy bear
hair drier
toothbrush
truthClassInt


In [0]:
image_col.remove('truthClassInt')

In [0]:
image_col

['person_y',
 'bicycle',
 'car_y',
 'motorcycle',
 'airplane',
 'bus',
 'train_y',
 'truck_y',
 'boat_y',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench_y',
 'bird_y',
 'cat_y',
 'dog_y',
 'horse',
 'sheep_y',
 'cow_y',
 'elephant',
 'bear_y',
 'zebra_y',
 'giraffe',
 'backpack_y',
 'umbrella_y',
 'handbag_y',
 'tie_y',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard_y',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup_y',
 'fork_y',
 'knife_y',
 'spoon',
 'bowl_y',
 'banana_y',
 'apple',
 'sandwich_y',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza_y',
 'donut_y',
 'cake_y',
 'chair_y',
 'couch',
 'potted plant',
 'bed_y',
 'dining table',
 'toilet_y',
 'tv_y',
 'laptop_y',
 'mouse',
 'remote',
 'keyboard_y',
 'cell phone',
 'microwave',
 'oven_y',
 'toaster_y',
 'sink_y',
 'refrigerator',
 'book_y',
 'clock_y',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier'

Fit the number of object appearance to [0,1] (NORMALIZE)

In [0]:
i = 0
for col_name in image_col:
  for i in range(len(final)):
    if final[col_name][i] >1:
      final.set_value(i, col_name, 1)
    #final[col_name][i] = min (final[col_name
  

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """


In [0]:
final.shape

(11429, 13763)

For fitting the model, we'll keep 1)vector representation of postText, 2) vector rep. of image(80 cols) and Y (truth which is binary)

In [0]:
col= ['id_y', 'postMedia', 'postText', 'postTimestamp', 'targetCaptions', 'targetDescription',	'targetKeywords',	'targetParagraphs',	'targetTitle',	'truthClass',	'truthJudgments',	'truthMean',	'truthMedian',	'truthMode']

In [0]:
len(col)

14

In [0]:
train_df = final.drop(col, axis = 1)

In [0]:
train_df.shape

(11429, 13748)

In [0]:
train_df.head(1)

00  016  070  070shake  10  100  1000  10000  100000  1000000  ...  sink_y  \
0   0    0    0         0   0    0     0      0       0        0  ...       0   

   refrigerator  book_y  clock_y  vase  scissors  teddy bear  hair drier  \
0             0       0        0     0         0           0           0   

   toothbrush  truthClassInt  
0           0              0  

[1 rows x 13749 columns]

In [0]:
train_df = train_df.drop('truthClassInt', axis=1)

In [0]:
label = pd.DataFrame(final['truthClassInt'])

In [0]:
label.shape

(11429, 1)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(train_df,label, test_size = 0.20)  
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(9143, 13748)
(2286, 13748)
(9143, 1)
(2286, 1)


**Classification starts**

In [0]:
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import f1_score,confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.neural_network import MLPClassifier

from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier, VotingClassifier

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

#from sklearn_evaluation import plot

In [0]:
def scoring_cv(classifier): #segmentation fault occurs
  scores = cross_val_score(classifier, X_train, Y_train, cv = 10, n_jobs=-1)
  print(scores)

In [0]:
def scoring (classifier):
  pred = classifier.predict(X_test)
  return (metrics.accuracy_score(Y_test, pred))

In [0]:
nb = MultinomialNB()
nb.fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
nb.score(X_test, Y_test)

0.794838145231846

In [0]:
Y_pred = nb.predict(X_test)
from sklearn import metrics
print(accuracy_score(Y_test, Y_pred))

0.794838145231846


In [0]:
scoring(nb)

0.794838145231846

In [0]:
#K-fold for Naive bayes
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.model_selection import cross_val_predict

predicted = cross_val_predict(MultinomialNB(), X_train, label_one_d, cv=10)
print(metrics.accuracy_score(label_one_d, predicted))
print(metrics.classification_report(label_one_d, predicted))

0.7921907470195778
              precision    recall  f1-score   support

           0       0.85      0.88      0.87      7075
           1       0.55      0.49      0.51      2068

   micro avg       0.79      0.79      0.79      9143
   macro avg       0.70      0.68      0.69      9143
weighted avg       0.78      0.79      0.79      9143



In [0]:
from sklearn.model_selection import cross_val_score
crossval_scores = cross_val_score(MultinomialNB(), X_train, label_one_d, scoring='roc_auc', cv=10)
crossval_scores

array([0.78707798, 0.79377508, 0.79364202, 0.80191872, 0.78002948,
       0.78016249, 0.7715666 , 0.81470321, 0.77523654, 0.80030486])

In [0]:
results = confusion_matrix(Y_test, Y_pred) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(Y_test, Y_pred)) 
print ('Report : ')
print (classification_report(Y_test, Y_pred))

Confusion Matrix :
[[1547  216]
 [ 253  270]]
Accuracy Score : 0.794838145231846
Report : 
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1763
           1       0.56      0.52      0.54       523

   micro avg       0.79      0.79      0.79      2286
   macro avg       0.71      0.70      0.70      2286
weighted avg       0.79      0.79      0.79      2286



In [0]:
#cross val predict only takes a 1-d vector
import numpy as np
label_one_d = np.ravel(Y_train)
print(np.ravel(Y_train))

[0 1 0 ... 0 0 0]


In [0]:
#K-fold for logistic regression
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict


logreg = LogisticRegression()
predicted = cross_val_predict(logreg, X_train, label_one_d, cv=10)
print(metrics.accuracy_score(label_one_d, predicted))
print(metrics.classification_report(label_one_d, predicted))


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

0.8182215902876517
              precision    recall  f1-score   support

           0       0.85      0.92      0.89      7075
           1       0.64      0.46      0.53      2068

   micro avg       0.82      0.82      0.82      9143
   macro avg       0.75      0.69      0.71      9143
weighted avg       0.80      0.82      0.81      9143



In [0]:
from sklearn.model_selection import cross_val_score
crossval_scores = cross_val_score(LogisticRegression(), X_train, label_one_d, scoring='roc_auc', cv=10)
crossval_scores

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

array([0.79099457, 0.81127692, 0.80552826, 0.84109828, 0.80021971,
       0.79482607, 0.79494223, 0.81887133, 0.8153074 , 0.811737  ])

2. Logistic Classification

In [0]:

logreg = LogisticRegression()
%time 
logreg.fit(X_train, Y_train)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
logreg.score(X_test, Y_test)

0.8232720909886264

3. SVM... because it takes longest time I assume

In [0]:
svm = SVC()
%time
svm.fit(X_train, Y_train)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 16.7 µs


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
svm.score(X_test, Y_test)

0.7712160979877515

In [0]:
Y_pred = svm.predict(X_test)
result = confusion_matrix(Y_test, Y_pred)
result

array([[1763,    0],
       [ 523,    0]])

In [0]:
from sklearn.svm import LinearSVR
Cs = [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1, 0.5, 1, 2, 4]
for c in Cs:
  svm2 = LinearSVR(C=c, loss='squared_epsilon_insensitive', dual= False, random_state=1)
  svm2.fit(X_train, Y_train)
  print(svm2.score(X_test, Y_test))
  Y_pred = svm2.predict(X_test)
  result = confusion_matrix(Y_test,Y_pred)
  print(result)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.027875998101572597


ValueError: ignored

In [0]:
def accuracy_info(clf):
  Y_pred= clf.predict(X_test)
  results = confusion_matrix(Y_test, Y_pred) 
  print ('Confusion Matrix :')
  print(results) 
  print ('Accuracy Score :',accuracy_score(Y_test, Y_pred)) 
  print ('Report : ')
  print (classification_report(Y_test, Y_pred))
  #AUC score...not sure
  y_pred_prob = clf.predict_proba(X_test)[:,-1]
  print('ROC AUC Score :',metrics.roc_auc_score(Y_test, y_pred_prob))
  





In [0]:
def training(clf):
  clf.fit(X_train, Y_train)

In [0]:
accuracy_info(logreg)

Confusion Matrix :
[[1630  133]
 [ 271  252]]
Accuracy Score : 0.8232720909886264
Report : 
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      1763
           1       0.65      0.48      0.56       523

   micro avg       0.82      0.82      0.82      2286
   macro avg       0.76      0.70      0.72      2286
weighted avg       0.81      0.82      0.81      2286

ROC AUC Score : 0.8133613289532335


In [0]:
len(Y_train),len(Y_test)

(9143, 2286)

Random Forest

In [0]:
rf = RandomForestClassifier()
training(rf)

NameError: ignored

In [0]:
#random forest k-fold information
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict

predicted = cross_val_predict(RandomForestClassifier(), X_train, label_one_d, cv=10)
print(metrics.accuracy_score(label_one_d, predicted))
print(metrics.classification_report(label_one_d, predicted))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

0.8041124357431915
              precision    recall  f1-score   support

           0       0.82      0.96      0.88      7075
           1       0.67      0.27      0.38      2068

   micro avg       0.80      0.80      0.80      9143
   macro avg       0.74      0.61      0.63      9143
weighted avg       0.78      0.80      0.77      9143



In [0]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score
rf = RandomForestClassifier()
score = cross_val_score(rf, X_train, label_one_d, cv=10)
score

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

array([0.78907104, 0.82076503, 0.79781421, 0.81639344, 0.80327869,
       0.79321663, 0.79102845, 0.81400438, 0.79079956, 0.79956188])

In [0]:
accuracy_info(rf)

Confusion Matrix :
[[1694   69]
 [ 391  132]]
Accuracy Score : 0.7987751531058618
Report : 
              precision    recall  f1-score   support

           0       0.81      0.96      0.88      1763
           1       0.66      0.25      0.36       523

   micro avg       0.80      0.80      0.80      2286
   macro avg       0.73      0.61      0.62      2286
weighted avg       0.78      0.80      0.76      2286

ROC AUC Score : 0.76799985684058


In [0]:
ls

after_stem.csv
b4stem.csv
b4vectorize.csv
big_df.csv
big_info.csv
clickbait17-train-170331/
clickbait17-train-170331.zip
clickbait17-train-170630/
clickbait17-train-170630.zip
Connect.ipynb
Conroy_et_al-2015-Proceedings_of_the_Association_for_Information_Science_and_Technology.pdf
faster_rcnn_inception_resnet_v2_atrous_coco_2017_11_08/
faster_rcnn_inception_resnet_v2_atrous_coco_2017_11_08.tar.gz
faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28/
faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz
final_clipping.csv
image_info.csv
image_info_numbercol.csv
integrated.csv
object_detection/
papers/
small_df.csv
src/
total_dataset/
vector_form.csv


Training with base df:

In [0]:
base.shape

(11429, 13669)

In [0]:
#get the labels
label1 = pd.DataFrame(base['truthClassInt'])
label1.shape

In [0]:
#get training set 
train_df1 = base.drop('truthClassInt', axis=1)
train_df1.shape

00  016  070  070shake  10  100  1000  10000  100000  1000000  ...  \
0       0    0    0         0   0    0     0      0       0        0  ...   
1       0    0    0         0   0    0     0      0       0        0  ...   
2       1    0    0         0   0    0     0      0       0        0  ...   
3       0    0    0         0   0    0     0      0       0        0  ...   
4       0    0    0         0   0    0     0      0       0        0  ...   
5       0    0    0         0   0    0     0      0       0        0  ...   
6       0    0    0         0   0    0     0      0       0        0  ...   
7       0    0    0         0   0    0     0      0       0        0  ...   
8       0    0    0         0   0    0     0      0       0        0  ...   
9       0    0    0         0   0    0     0      0       0        0  ...   
10      0    0    0         0   0    0     0      0       0        0  ...   
11      0    0    0         0   0    0     0      0       0        0  ...   
12      0    0    0         0   0    0     0      0       0        0  ...   
13      0    0    0         0   0    0     0      0       0        0  ...   
14      0    0    0         0   0    0     0      0       0        0  ...   
15      0    0    0         0   0    0     0      0       0        0  ...   
16      0    0    0         0   0    0     0      0       0        0  ...   
17      0    0    0         0   0    0     0      0       0        0  ...   
18      0    0    0         0   0    0     0      0       0        0  ...   
19      0    0    0         0   0    0     0      0       0        0  ...   
20      0    0    0         0   0    0     0      0       0        0  ...   
21      0    0    0         0   0    0     0      0       0        0  ...   
22      0    0    0         0   0    0     0      0       0        0  ...   
23      0    0    0         0   0    0     0      0       0        0  ...   
24      0    0    0         0   0    0     0      0       0        0  ...   
25      0    0    0         0   0    0     0      0       0        0  ...   
26      0    0    0         0   0    0     0      0       0        0  ...   
27      0    0    0         0   0    0     0      0       0        0  ...   
28      0    0    0         0   0    0     0      0       0        0  ...   
29      0    0    0         0   0    0     0      0       0        0  ...   
...    ..  ...  ...       ...  ..  ...   ...    ...     ...      ...  ...   
11399   0    0    0         0   0    0     0      0       0        0  ...   
11400   0    0    0         0   0    0     0      0       0        0  ...   
11401   0    0    0         0   0    0     0      0       0        0  ...   
11402   0    0    0         0   0    0     0      0       0        0  ...   
11403   0    0    0         0   0    0     0      0       0        0  ...   
11404   0    0    0         0   0    0     0      0       0        0  ...   
11405   0    0    0         0   0    0     0      0       0        0  ...   
11406   0    0    0         0   0    0     0      0       0        0  ...   
11407   0    0    0         0   0    0     0      0       0        0  ...   
11408   0    0    0         0   0    0     0      0       0        0  ...   
11409   0    0    0         0   0    0     0      0       0        0  ...   
11410   0    0    0         0   0    0     0      0       0        0  ...   
11411   0    0    0         0   0    0     0      0       0        0  ...   
11412   0    0    0         0   0    0     0      0       0        0  ...   
11413   0    0    0         0   0    0     0      0       0        0  ...   
11414   0    0    0         0   0    0     0      0       0        0  ...   
11415   0    0    0         0   0    0     0      0       0        0  ...   
11416   0    0    0         0   0    0     0      0       0        0  ...   
11417   0    0    0         0   0    0     0      0       0        0  ...   
11418   0    0    0         0   0    0     1      0       0        0  ...   
114

In [0]:
from sklearn.model_selection import train_test_split
X_train_base, X_test_base, Y_train_base, Y_test_base = train_test_split(train_df1,label1, test_size = 0.20)  
print(X_train_base.shape)
print(X_test_base.shape)
print(Y_train_base.shape)
print(Y_test_base.shape)

NameError: ignored

In [0]:
#Naive bayes on base
nb = MultinomialNB()
nb.fit(X_train_base, Y_train_base)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
nb.score(X_test_base, Y_test_base)

0.799650043744532

In [0]:
Y_pred = nb.predict(X_test_base)
from sklearn import metrics
print(accuracy_score(Y_test_base, Y_pred))

0.799650043744532


In [0]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
%time 
logreg.fit(X_train_base, Y_train_base)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 6.2 µs


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
logreg.score(X_test_base, Y_test_base)

0.8202099737532809

In [0]:
#linear regression just post text---should we do this?
lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
predictions = lm.predict(X_test)

In [0]:
base.shape

(11429, 13669)

In [0]:
base.head(2)

00  016  070  070shake  10  100  1000  10000  100000  1000000  ...  zone  \
0   0    0    0         0   0    0     0      0       0        0  ...     0   
1   0    0    0         0   0    0     0      0       0        0  ...     0   

   zoo  zoom  zs  zsa  zshanlon  zuckerberg  zuma  zurich  truthClassInt  
0    0     0   0    0         0           0     0       0              0  
1    0     0   0    0         0           0     0       0              1  

[2 rows x 13669 columns]

In [0]:
base.to_csv(r'/content/Drive/My Drive/Spring 2019/ML/sample for project/text_vectorized.csv', index=False)